package us.ihmc.scs2.simulation.mujoco.physicsEngine;

import java.util.ArrayList;
import java.util.List;

import org.bytedeco.javacpp.BytePointer;
import org.bytedeco.javacpp.DoublePointer;

import us.ihmc.euclid.tuple3D.interfaces.Vector3DReadOnly;
import us.ihmc.scs2.simulation.mujoco.Mujoco;
import us.ihmc.scs2.simulation.mujoco.Mujoco.mjContact;
import us.ihmc.scs2.simulation.mujoco.Mujoco.mjData;
import us.ihmc.scs2.simulation.mujoco.Mujoco.mjModel;

/**
 * Owns the compiled `mjModel` and the runtime `mjData` for a single MuJoCo simulation.
 *
 * <p>v1 design: a MuJoCo simulation is one composite MJCF document that includes every robot's
 * URDF plus the terrain geoms. We assemble the MJCF text in {@link MujocoMultiBodyRobotFactory}
 * and call {@link #compile(String)} exactly once, then step the world from
 * {@link us.ihmc.scs2.simulation.mujoco.physicsEngine.MujocoPhysicsEngine#simulate}.
 *
 * <p>Adding robots after the world is compiled would require rebuilding `mjModel`, which MuJoCo
 * supports via `mjSpec` but is out of scope for v1.
 */
public class MujocoMultiBodyDynamicsWorld
{
   private mjModel model;
   private mjData data;
   private final List<MujocoMultiBodyRobot> robots = new ArrayList<>();
   private final List<MujocoTerrainObject> terrainObjects = new ArrayList<>();

   /**
    * Compiles the supplied MJCF text into {@code mjModel} + {@code mjData}.
    *
    * <p>{@code mj_loadXML} only accepts a file path, so the XML is written to {@code mjcfFile}
    * first (which {@link MujocoMultiBodyRobotFactory} typically places in a per-session working
    * directory next to the per-robot URDF includes).
    */
   public void compile(String mjcfXml, java.io.File mjcfFile)
   {
      if (model != null || data != null)
         throw new IllegalStateException("MuJoCo model already compiled. Multiple compiles per world are not supported in v1.");

      try
      {
         java.nio.file.Files.writeString(mjcfFile.toPath(), mjcfXml);
      }
      catch (java.io.IOException e)
      {
         throw new RuntimeException("Could not write MJCF to " + mjcfFile, e);
      }

      BytePointer errorBuffer = new BytePointer(1000);
      model = Mujoco.mj_loadXML(mjcfFile.getAbsolutePath(), null, errorBuffer, 1000);
      if (model == null || model.isNull())
      {
         throw new RuntimeException("mj_loadXML failed: " + errorBuffer.getString());
      }
      data = Mujoco.mj_makeData(model);
      if (data == null || data.isNull())
         throw new RuntimeException("mj_makeData failed (out of memory?)");
   }

   public mjModel getModel()
   {
      return model;
   }

   public mjData getData()
   {
      return data;
   }

   public List<MujocoMultiBodyRobot> getRobots()
   {
      return robots;
   }

   public List<MujocoTerrainObject> getTerrainObjects()
   {
      return terrainObjects;
   }

   public void addMujocoRobot(MujocoMultiBodyRobot robot)
   {
      robots.add(robot);
   }

   public void addMujocoTerrainObject(MujocoTerrainObject terrainObject)
   {
      terrainObjects.add(terrainObject);
   }

   public void setGravity(Vector3DReadOnly gravity)
   {
      if (model == null)
         return;
      // mjOption.gravity is an mjtNum[3]. Mutate in place via JavaCPP pointer indexing.
      DoublePointer gravityPointer = model.opt().gravity();
      gravityPointer.put(0, gravity.getX());
      gravityPointer.put(1, gravity.getY());
      gravityPointer.put(2, gravity.getZ());
   }

   public void step()
   {
      Mujoco.mj_step(model, data);
      // mj_step only computes cfrc_ext / cfrc_int when MJCF sensors require them. We read
      // cfrc_ext directly per-tick in MujocoRobot.updateSensors so the F/T sensor plumbing has
      // contact wrenches to integrate; force the post-constraint pass here unconditionally.
      Mujoco.mj_rnePostConstraint(model, data);
   }

   public void step(int substeps)
   {
      for (int i = 0; i < substeps; i++)
         Mujoco.mj_step(model, data);
      Mujoco.mj_rnePostConstraint(model, data);
   }

   public double getTimestep()
   {
      return model.opt().timestep();
   }

   public void setTimestep(double dt)
   {
      // mjOption is a struct value; the generated wrapper exposes it via accessors. The setter for
      // timestep is auto-generated by JavaCPP.
      model.opt().timestep(dt);
   }

   // Once-per-sim-second contact dump. Hypothesis-validator for the foot-flat box-on-plane
   // contact: MuJoCo should be generating ~4 contact points at the foot polygon corners during
   // stance, not a single point contact. If ncon is consistently 1 or 2 during foot-flat stance,
   // the box-box specialized routine isn't firing as expected and we need to revisit.
   private double nextContactLogTime = 0.0;
   private static final double CONTACT_LOG_PERIOD_SECONDS = 1.0;

   public void logContactsIfDue(double currentTime)
   {
      if (currentTime < nextContactLogTime)
         return;
      nextContactLogTime = currentTime + CONTACT_LOG_PERIOD_SECONDS;
      if (model == null || data == null)
         return;

      int ncon = data.ncon();
      StringBuilder line = new StringBuilder();
      line.append(String.format("[MujocoWorld] t=%6.2fs ncon=%d", currentTime, ncon));
      if (ncon == 0)
      {
         System.out.println(line);
         return;
      }
      System.out.println(line);

      mjContact contact = data.contact();
      for (int i = 0; i < ncon; i++)
      {
         contact.position(i);
         int g1 = contact.geom1();
         int g2 = contact.geom2();
         double px = contact.pos(0);
         double py = contact.pos(1);
         double pz = contact.pos(2);
         double dist = contact.dist();
         int dim = contact.dim();
         String g1Name = geomNameOrId(g1);
         String g2Name = geomNameOrId(g2);
         System.out.printf("  c%d: %s / %s pos=(%.3f,%.3f,%.4f) dist=%+.4f dim=%d%n",
                           i, g1Name, g2Name, px, py, pz, dist, dim);
      }
   }

   private String geomNameOrId(int geomId)
   {
      if (geomId < 0)
         return "<none>";
      BytePointer name = Mujoco.mj_id2name(model, Mujoco.mjOBJ_GEOM, geomId);
      if (name == null || name.isNull())
         return "geom#" + geomId;
      String s = name.getString();
      return s.isEmpty() ? "geom#" + geomId : s;
   }

   public void dispose()
   {
      if (data != null && !data.isNull())
      {
         Mujoco.mj_deleteData(data);
         data = null;
      }
      if (model != null && !model.isNull())
      {
         Mujoco.mj_deleteModel(model);
         model = null;
      }
      robots.clear();
      terrainObjects.clear();
   }
}
